### ISSUE TITLE
assertive not running in ansible tower

### ISSUE THREAD

**Issue by mirzawaqasahmed** [larsks/ansible-assertive#9]
Hi, I have tried to run the assertive plugin in tower but it doesnt seem to run it. 
I get the following out put on the job run in ansible tower.
```
[WARNING]: Skipping plugin
(/var/lib/awx/projects/_25__lab_f5_score_proj/callback_plugins/assertive.py) as
it seems to be invalid: 'module' object has no attribute 'add_representer'
```
I have successfully tested it without tower.

Any suggestion?

**Comment by danielbjorkholm** [comment]
Any news on this?

**Comment by larsks** [comment]
Sorry for the slow response. It turns out that this plugin is tied fairly tightly to a particular Ansible version. It's unlikely I'm going to spend the time chasing future compatibility. It was a neat idea but I'm not using it in practice.  I'm going to mark this project as read-only.
